site_name: pyfast-ui
site_description: Program for interative processing of FastSPM movies
site_url: https://matkrin.github.io/pyfast-ui

theme:
  name: "material"
  features:
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

repo_name: matkrin/pyfast-ui
repo_url: https://github.com/matkrin/pyfast-ui

nav:
- Home: index.md
- Usage: usage.md
- Development:
  - MainGui: api/main_gui.md
  - MovieWindow: api/movie_window.md
  - HistogramWindow: api/histogram_window.md
  - Groups: api/groups.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [.]
        options:
          show_root_heading: true
          show_category_heading: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_root_toc_entry: true
          show_source: false
          show_signature_annotations: true
          # show_if_no_docstring: true
          # separate_signature: true
          heading_level: 1
          summary: true


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
